runtime: nodejs20
service: default
# env: flex  # atau 'standard' tergantung kebutuhan

# # Konfigurasi untuk static site
# handlers:
#   - url: /(.*\.(js|css|png|jpg|ico|json))$
#     static_files: build/\1
#     upload: build/(.*\.(js|css|png|jpg|ico|json))$
#     expiration: '10m'

#   - url: /(.*)
#     static_files: build/index.html
#     upload: build/index.html
#     http_headers:
#       Cache-Control: 'no-cache, no-store, must-revalidate'
#       Pragma: 'no-cache'
#       Expires: '0'

# # Atau untuk SSR (jika menggunakan Next.js)
# # runtime_config:
# #   min_num_instances: 1
# #   max_num_instances: 3
# #   cpu: 1
# #   memory_gb: 0.5

# automatic_scaling:
#   min_instances: 1
#   max_instances: 3

# env_variables:
#   NODE_ENV: 'production'